spring.application.name=user-service
server.port=3002

spring.data.mongodb.uri=mongodb+srv://sspool2025:SSpool25%24%2A@pool-mate-cluster.tbu4cpm.mongodb.net/SyncRide-Users?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=false
jwt.secret=a880292d4305184e21cc8d653c52bc62e896655c25feb2bffc721a82840f6da856677f4830c9b398020a99b696b8d63f22cff0ad4c84084842f9a1a6ff51796f

# Cloudinary
cloudinary.cloud-name=dbmuy7nhi
cloudinary.api-key=588658242162333
cloudinary.api-secret=UFBh7SYUfVM0IJDpoReugUkQNmI


spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=30MB