server.port=3006
jwt.secret=a880292d4305184e21cc8d653c52bc62e896655c25feb2bffc721a82840f6da856677f4830c9b398020a99b696b8d63f22cff0ad4c84084842f9a1a6ff51796f

# #DB connection
spring.data.mongodb.uri=mongodb+srv://sspool2025:SSpool25%24%2A@pool-mate-cluster.tbu4cpm.mongodb.net/SyncRide-Organizations?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=false

# # User-service base URL (called to register admin users)
 user.service.url=http://localhost:3002
